load '/Users/prsurya/Desktop/ruby/blue/blue/token.rb'
load '/Users/prsurya/Desktop/ruby/blue/blue/lexer.rb'
load '/Users/prsurya/Desktop/ruby/blue/blue/ast.rb'
load '/Users/prsurya/Desktop/ruby/blue/blue/parser.rb'
load '/Users/prsurya/Desktop/ruby/blue/blue/object.rb'
load '/Users/prsurya/Desktop/ruby/blue/blue/evaluator.rb'
